CREATE DATABASE IF NOT EXISTS Blog;

CREATE TABLE IF NOT EXISTS Post(
id VARCHAR(3) PRIMARY KEY,
name VARCHAR(255),
date TIMESTAMP
);

SET DATESTYLE TO 'ISO, MDY';

CREATE TABLE IF NOT EXISTS Content(
id VARCHAR(3) references Post(id), 
text TEXT PRIMARY KEY

);

CREATE TABLE FI NOT EXISTS Decoration(
id VARCHAR(3) references Post(id),
archive TEXT PRIMARY KEY
);